ALTER TABLE musica ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
ALTER TABLE tag ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
ALTER TABLE genero_musical ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
ALTER TABLE musica_da_tag ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
ALTER TABLE genero_da_musica ADD COLUMN ativo BOOLEAN DEFAULT TRUE;