-- Tabela de permissões atômicas
CREATE TABLE permissions (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- Tabela de papéis
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)  NOT NULL UNIQUE
);

-- Junção roles <-> permissions
CREATE TABLE roles_permissions (
    role_id       BIGINT NOT NULL REFERENCES roles(id),
    permission_id BIGINT NOT NULL REFERENCES permissions(id),
    PRIMARY KEY (role_id, permission_id)
);

-- Junção users <-> roles
CREATE TABLE user_roles (
    user_id UUID   NOT NULL REFERENCES usuario(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);

